jaffle_shop: # this needs to match the profile: in your dbt_project.yml file
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 4
      account: <account_id> # supplied to you, eg. pa19123 (do not include the `snowflakecomputing.com` part)
      user: <username> # supplied to you
      password: <password> # supplied to you, you should have been asked to reset it when you opened the Snowflake console
      role: transformer
      database: analytics
      warehouse: transforming
      schema: dev_<initialsurname> # e.g. dev_ccarroll
      client_session_keep_alive: False
